Page.create! name: "Scheduling Text", content:"You have successfully registered for New Student Orientation on {{ registration.orientation.friendly_date }} at {{ registration.orientation.class_time}}. Please arrive 10 minutes prior to your scheduled Orientation. Remember, you must attend this Orientation session before you may register for classes. </p> <p> LOCATION Your one and a half hour, lab based New Student Orientation will be held in the Ferguson Building, room 112. <p> A Campus Map, is available. Ferguson is building number 8 on the map. Most convenient parking to the Ferguson Building is in lots A2-A5. </p> <p> Parking can be tight while classes are in session, so give yourself extra time to find parking and walk to Ferguson 112. Park in white lined spaces only! </p> <p> Please refrain from bringing food and beverages into the Orientation Room. Guests are not allowed in the New Student Orientation room. </p> <p> To schedule an optional campus tour, please visit newstudents.abtech.edu/campus_tour/ "

Page.create! name: "Scheduling Email", content: "You have successfully registered for New Student Orientation on {{ registration.orientation.friendly_date }} at {{ registration.orientation.class_time }}. Please arrive 10 minutes prior to your scheduled Orientation. Please remember, you must attend this Orientation session before you may register for classes. LOCATION Your one and a half hour, lab based New Student Orientation will be held in the Ferguson Building, room 112. For a Campus Map, please visit www.abtech.edu/content/a-b-tech-locations/asheville-campus. Ferguson is building number 8 on the map. Most convenient parking to the Ferguson Building is in lots A2-A5. Parking can be tight while classes are in session, so give yourself extra time to find parking and walk to the Ferguson 112. Park in white lined spaces only! Please refrain from bringing food and beverages into the Orientation Room. Guests are not allowed in the New Student Orientation room. To schedule an optional campus tour, please visit newstudents.abtech.edu/campus_tour/"

Page.create! name: "Online Registration Text", content: "Congratulations! You have successfully registered for the online New Student Orientation (NSO), which is offered through Moodle. Your Moodle account will be created within 4-6 hours and your course will be available. Once your account has been created, you can begin the orientation. You will need to: Login to moodle.abtech.edu, under My Courses go to NSO Username: first name, middle initial, last name (johnqstudent) Password: your WebAdvisor password If you are unable to login, contact the helpdesk at helpdesk@abtech.edu or 828-398-7550. If you are new to Moodle, a video tour is available at moodle.abtech.edu. ALL students are required to successfully complete New Student Orientation (NSO) before registering for classes. Successful completion requires passing the Assessment at the end of the course with an 80% or higher. Assessments are uploaded and registration restrictions are lifted on weekdays at 9 AM, 12 PM, 3 PM and 6 PM. Please be sure to plan ahead!"

Page.create! name: "Online Registration Email", content: "Congratulations! You have successfully registered for the online New Student Orientation (NSO), which is offered through Moodle. Your Moodle account will be created within 4-6 hours and your course will be available. Once your account has been created, you can begin the orientation. You will need to: Login to moodle.abtech.edu, under My Courses go to NSO Username: first name, middle initial, last name (johnqstudent) Password: your WebAdvisor password If you are unable to login, contact the helpdesk at helpdesk@abtech.edu or 828-398-7550. If you are new to Moodle, a video tour is available at moodle.abtech.edu. ALL students are required to successfully complete New Student Orientation (NSO) before registering for classes. Successful completion requires passing the Assessment at the end of the course with an 80% or higher. Assessments are uploaded and registration restrictions are lifted on weekdays at 9 AM, 12 PM, 3 PM and 6 PM. Please be sure to plan ahead!"

Page.create! name: "Cancel Confirmation Email", content: "This is a verification that you want to cancel your scheduled A-B Tech New Student Orientation session for {{ registration.orientation.friendly_date }}  at {{ registration.orientation.class_time}}. If you do not want to cancel your scheduled orientation, ignore this email. Please be advised, that you will need to reschedule and attend orientation before you may register for classes. If you wish to proceed with canceling your current orientation session, click the Destroy Registration link below."

Page.create! name: "Cancel Confirmation Text", content: "You have successfully cancelled your registration for the A-B Tech New Student Orientation session scheduled for {{ registration.orientation.friendly_date }}  at {{ registration.orientation.class_time}}. You will need to reschedule and attend orientation before you may register for classes. To reschedule fo to www.abtech.edu/nso."

Page.create! name: "Reminder Email", content: "Hello {{ registration.first_name }}. This is a reminder that you are scheduled to attend the A-B Tech New Student Orientation on {{ registration.orientation.friendly_date }}  at {{ registration.orientation.class_time }}. <p> Please arrive 10 minutes prior to your scheduled Orientation. Please remember, you must attend this Orientation session before you may register for classes. <p> LOCATION <p> Your two-hour, lab based New Student Orientation will be held in the Ferguson Building, room 112. <p> For a Campus Map, please visit www.abtech.edu/content/a-b-tech-locations/asheville-campus. Ferguson is building number 8 on the map. Most convenient parking to the Ferguson Building is in lots A2-A5. <p> Parking can be tight while classes are in session, so give yourself extra time to find parking and walk to Ferguson 112. Park in white lined spaces only! <p> Please refrain from bringing food and beverages into the Orientation Room. Guests are not allowed in the New Student Orientation room. <p> To schedule an optional campus tour, please visit abtech.edu/campus_tour/ <p> We look forward to seeing you! "
